#!/usr/bin/env bash
# shellcheck disable=SC2155
set -euo pipefail
trap "exit" INT
# shellcheck source=./../../dev/lib/utils.sh
source "${BASH_SOURCE%/*}/../../dev/lib/utils.sh"

NAME="libffi"
REPO_URL="https://github.com/libffi/libffi"
VERSION="3.4.6"

export CROSS_COMPILE="${CROSS_COMPILE:?}"
export BUILD_TIME="${BUILD_TIME:?}"
export BUILD_DIR="${BUILD_DIR:?}"
export INSTALL_DIR="${INSTALL_DIR:?}"
export OUT_DIR="${OUT_DIR:?}"

build_dir="$(abspath "${BUILD_DIR}")"
install_dir="$(abspath "${INSTALL_DIR}")"
out_dir="$(abspath "${OUT_DIR}")"

mkdir -p "${build_dir}"
pushd "${build_dir}" >/dev/null
{
  src_dir="${NAME}-${VERSION}"

  if [ ! -d "${src_dir}" ]; then
    nicely git clone --quiet --recursive --depth=1 -b "v${VERSION}" "${REPO_URL}" "${src_dir}"
    pushd "${src_dir}" >/dev/null
    {
      nicely ./autogen.sh | log "${build_dir}/build.log"
    }
    popd >/dev/null
  fi

  pushd "${src_dir}" >/dev/null
  {

    nicely ./configure \
      --prefix="${install_dir}" \
      --disable-multi-os-directory \
      --disable-docs \
      --enable-shared=no \
      --enable-static=yes \
      2>&1 | log "${build_dir}/build.log"

    nicely make -s -j"${JOBS}" 2>&1 | log "${build_dir}/build.log"
    nicely make -s install 2>&1 | log "${build_dir}/build.log"

    sed -i "s|prefix=${INSTALL_DIR}|prefix=\$\{pcfiledir\}/../..|g" "${INSTALL_DIR}/lib/pkgconfig/${NAME}.pc"

    package_all "${install_dir}" "${out_dir}/${NAME}-${VERSION}-static-${CROSS_COMPILE}-${BUILD_TIME}"
  }
  popd >/dev/null
}
popd >/dev/null
