#!/usr/bin/env bash
# shellcheck disable=SC2155
set -euo pipefail
trap "exit" INT
# shellcheck source=./../lib/utils.sh
source "${BASH_SOURCE%/*}/../lib/utils.sh"

function build() {
  trap "exit" INT

  local name="${1:?}"
  declare -x CROSS_COMPILE="${2:-${CROSS_COMPILE:?}}"
  declare -x BUILD_TIME="${BUILD_TIME:-"$(datetime_safe)"}"
  declare -x BUILD_DIR="${BUILD_DIR:-"$(project_root)/.build/${CROSS_COMPILE}"}"
  declare -x INSTALL_DIR="${INSTALL_DIR:-"$(project_root)/.install/${CROSS_COMPILE}/${BUILD_TIME}"}"
  declare -x OUT_DIR="${OUT_DIR:-"$(project_root)/.out/${BUILD_TIME}"}"

  declare -x SYSROOT="${CROSS_SYSROOT:?}"
  declare -x CC="$(getenv_cross "CC" "${CROSS_COMPILE}")"
  declare -x CXX="$(getenv_cross "CXX" "${CROSS_COMPILE}")"
  declare -x FC="$(getenv_cross "FC" "${CROSS_COMPILE}")"
  declare -x ADDR2LINE="$(getenv_cross "ADDR2LINE" "${CROSS_COMPILE}")"
  declare -x AR="$(getenv_cross "AR" "${CROSS_COMPILE}")"
  declare -x AS="$(getenv_cross "AS" "${CROSS_COMPILE}")"
  declare -x CPP="$(getenv_cross "CPP" "${CROSS_COMPILE}")"
  declare -x ELFEDIT="$(getenv_cross "ELFEDIT" "${CROSS_COMPILE}")"
  declare -x LD="$(getenv_cross "LD" "${CROSS_COMPILE}")"
  declare -x LDD="$(getenv_cross "LDD" "${CROSS_COMPILE}")"
  declare -x NM="$(getenv_cross "NM" "${CROSS_COMPILE}")"
  declare -x OBJCOPY="$(getenv_cross "OBJCOPY" "${CROSS_COMPILE}")"
  declare -x OBJDUMP="$(getenv_cross "OBJDUMP" "${CROSS_COMPILE}")"
  declare -x RANLIB="$(getenv_cross "RANLIB" "${CROSS_COMPILE}")"
  declare -x READELF="$(getenv_cross "READELF" "${CROSS_COMPILE}")"
  declare -x SIZE="$(getenv_cross "SIZE" "${CROSS_COMPILE}")"
  declare -x STRINGS="$(getenv_cross "STRINGS" "${CROSS_COMPILE}")"
  declare -x STRIP="$(getenv_cross "STRIP" "${CROSS_COMPILE}")"

  declare -x CCACHE_DIR="$(get_cache_dir "${CROSS_COMPILE}")/ccache"
  declare -x CCACHE_NOCOMPRESS="1"
  declare -x CCACHE_MAXSIZE="50G"
  declare -x CMAKE_C_COMPILER_LAUNCHER="ccache"
  declare -x CMAKE_CXX_COMPILER_LAUNCHER="ccache"

  local c_arch
  case "${CROSS_COMPILE}" in
  aarch64-apple* | aarch64-darwin*)
    c_arch="-mcpu=apple-m1"
    ;;
  aarch64*)
    c_arch="-march=armv8.2-a"
    ;;
  x86_64*)
    c_arch="-march=haswell"
    ;;
  esac

  local opt_flags="-fPIC -g0 -O3 -ftree-vectorize -funroll-loops"
  local sysroot="--sysroot=${CROSS_SYSROOT}"

  local static_flags=
  if [[ "${CROSS_COMPILE}" =~ (apple|darwin) ]]; then
    static_flags="-static-libstdc++"
  else
    static_flags="" #"-static -static-libgcc -static-libgfortran -static-libstdc++"
  fi

  local common_flags="-w ${opt_flags} ${static_flags} ${c_arch} ${sysroot}"
  local cflags=""
  local cxxflags=""
  local fcflags=""
  local ldflags="-s"

  declare -x CFLAGS="${CFLAGS:-} ${common_flags} ${cflags}"
  declare -x CXXFLAGS="${CXXFLAGS:-} ${common_flags} ${cxxflags}"
  declare -x FCFLAGS="${FCFLAGS:-} ${common_flags} ${fcflags}"
  declare -x LDFLAGS="${LDFLAGS:-} ${common_flags} ${ldflags}"

  nicely "$(project_root)/libs/${name}/build"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  build "$@"
fi
