#!/usr/bin/env bash
# shellcheck disable=SC2155
set -euo pipefail
trap "exit" INT
# shellcheck source=./../../dev/lib/utils.sh
source "${BASH_SOURCE%/*}/../../dev/lib/utils.sh"

NAME="bzip2"
VERSION="1.0.8"
TARBALL_URL="https://sourceware.org/pub/bzip2/bzip2-${VERSION}.tar.gz"

export CROSS_COMPILE="${CROSS_COMPILE:?}"
export BUILD_TIME="${BUILD_TIME:?}"
export BUILD_DIR="${BUILD_DIR:?}"
export INSTALL_DIR="${INSTALL_DIR:?}"
export OUT_DIR="${OUT_DIR:?}"

build_dir="$(abspath "${BUILD_DIR}")"
install_dir="$(abspath "${INSTALL_DIR}")"
out_dir="$(abspath "${OUT_DIR}")"

mkdir -p "${build_dir}"
pushd "${build_dir}" >/dev/null
{
  src_dir=$(abspath "${NAME}-${VERSION}")

  if [ ! -d "${src_dir}" ]; then
    fetch_tarball "${TARBALL_URL}" "${src_dir}" --strip-components=1
  fi

  pushd "${src_dir}" >/dev/null
  {
    export CC="ccache ${CC} ${CFLAGS} -D_FILE_OFFSET_BITS=64"

    make CC="${CC}" AR="${AR}" RANLIB="${RANLIB}" LDFLAGS="${LDFLAGS}" PREFIX="${install_dir}" \
      "libbz2.a" -j"${JOBS}" 2>&1 | log "${build_dir}/build.log"

    nicely mkdir -p "${install_dir}/"{include,lib/pkgconfig}
    nicely cp "${src_dir}/libbz2.a" "${install_dir}/lib/"
    nicely cp "${src_dir}/bzlib.h" "${install_dir}/include/"

    cat <<EOF >"${install_dir}/lib/pkgconfig/${NAME}.pc"
prefix=\${pcfiledir}/../..
exec_prefix=\${prefix}
libdir=\${exec_prefix}/lib
includedir=\${prefix}/include

Name: bzip2
Description: A high-quality block-sorting file compressor library
Version: 1.0.8
Libs: -L\${libdir} -lbz2
Cflags: -I\${includedir}

EOF

    package_all "${install_dir}" "${out_dir}/${NAME}-${VERSION}-static-${CROSS_COMPILE}-${BUILD_TIME}"
  }
  popd >/dev/null
}
popd >/dev/null
