#!/usr/bin/env bash
# shellcheck disable=SC2155
set -euo pipefail
trap "exit" INT
# shellcheck source=./../../dev/lib/utils.sh
source "${BASH_SOURCE%/*}/../../dev/lib/utils.sh"

NAME="zstd"
REPO_URL="https://github.com/facebook/zstd"
VERSION="1.5.6"

export CROSS_COMPILE="${CROSS_COMPILE:?}"
export BUILD_TIME="${BUILD_TIME:?}"
export BUILD_DIR="${BUILD_DIR:?}"
export INSTALL_DIR="${INSTALL_DIR:?}"
export OUT_DIR="${OUT_DIR:?}"

build_dir="$(abspath "${BUILD_DIR}")"
install_dir="$(abspath "${INSTALL_DIR}")"
out_dir="$(abspath "${OUT_DIR}")"

mkdir -p "${build_dir}"
pushd "${build_dir}" >/dev/null
{
  src_dir="${NAME}-${VERSION}"

  if [ ! -d "${src_dir}" ]; then
    nicely git clone --quiet --recursive --depth=1 -b "v${VERSION}" "${REPO_URL}" "${src_dir}"
  fi

  pushd "${src_dir}" >/dev/null
  {
    nicely cmake -S "build/cmake" -B "build" \
      -Wno-dev -Wno-deprecated \
      -DCMAKE_INSTALL_PREFIX="${install_dir}" \
      -DCMAKE_INSTALL_LIBDIR="lib" \
      -DCMAKE_INSTALL_INCLUDEDIR="include" \
      -DCMAKE_BUILD_TYPE="Release" \
      -DCMAKE_VERBOSE_MAKEFILE="OFF" \
      \
      -DBUILD_SHARED_LIBS="OFF" \
      -DBUILD_STATIC_LIBS="ON" \
      \
      -DCMAKE_INSTALL_LIBDIR="lib" \
      \
      -DZSTD_BUILD_CONTRIB="OFF" \
      -DZSTD_BUILD_PROGRAMS="OFF" \
      -DZSTD_BUILD_SHARED="OFF" \
      2>& \
      1 | log "${build_dir}/build.log"

    nicely cmake --build "build" --parallel="${JOBS}" -- 2>&1 | log "${build_dir}/build.log"

    nicely cmake --install "build" 2>&1 | log "${build_dir}/build.log"

    sed -i "s|prefix=${install_dir}|prefix=\$\{pcfiledir\}/../..|g" "${install_dir}/lib/pkgconfig/libzstd.pc"

    package_all "${install_dir}" "${out_dir}/${NAME}-${VERSION}-static-${CROSS_COMPILE}-${BUILD_TIME}"
  }
  popd >/dev/null
}
popd >/dev/null
